version: "3"    
services:
  dev: 
    links:
      - actor0
  actor0:
    image: nicolasdorier/clightning:v0.6-bench
    privileged: true
    environment: 
      EXPOSE_TCP: "true"
      LIGHTNINGD_OPT: |
        bitcoin-datadir=/etc/bitcoin
        bitcoin-rpcconnect=miner
        network=regtest
        bind-addr=0.0.0.0
        announce-addr=actor0
        log-level=broken
        dev-broadcast-interval=1000
        ignore-fee-limits=true
    ports:
      - "24736:9835" # api port
    expose:
      - "9735" # server port
      - "9835" # api port
    volumes:
      - "btc_datadir:/etc/bitcoin"
      - "actor0_datadir:/root/.lightning"
      - "./actor0_traces:/opt/traces"
    links:
      - miner
volumes:
    actor0_datadir:
